name: restaurant
description: Fraved Restaurante Copyright 2022

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.3.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.4.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.5
  image_picker: ^1.0.4
  form_field_validator: ^1.1.0
  android_intent_plus: ^4.0.2
  shimmer: ^3.0.0
  carousel_slider: ^4.1.1
  geolocator: ^10.1.0
  google_maps_flutter: ^2.2.5
  permission_handler: ^11.0.0
  geocoding: ^2.1.0
  intl: ^0.18.1
  polyline_do: ^0.1.0
  url_launcher: ^6.1.10
  socket_io_client: ^2.0.3+1
  firebase_messaging: ^14.4.1
  firebase_core: ^2.10.0
  flutter_local_notifications: ^15.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - Assets/
    - Assets/Logo/
    - Assets/svg/


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

